src/Imi.Project.Vue/Models/ErrorViewModel.cs
using System;

namespace Imi.Project.Vue.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Imi.Project.Vue/Controllers/AnimeController.cs
using Imi.Project.Vue.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Imi.Project.Vue.Controllers
{
    public class AnimeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Imi.Project.Vue/Controllers/DirectorController.cs
using Imi.Project.Vue.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Imi.Project.Vue.Controllers
{
    public class DirectorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Imi.Project.Vue/Controllers/GenreController.cs
using Imi.Project.Vue.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Imi.Project.Vue.Controllers
{
    public class GenreController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Imi.Project.Vue/Controllers/HomeController.cs
using Imi.Project.Vue.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Imi.Project.Vue.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Imi.Project.Vue/Controllers/MovieController.cs
using Imi.Project.Vue.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Imi.Project.Vue.Controllers
{
    public class MovieController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Imi.Project.Vue/Controllers/TopTenMoviesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Imi.Project.Vue.Controllers
{
    public class TopTenMoviesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Imi.Project.Vue/Controllers/UserController.cs
using Imi.Project.Vue.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Imi.Project.Vue.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Register()
        {
            return View();
        }

        public IActionResult Logout()
        {
            return View();
        }
    }
}

src/Imi.Project.Vue/Views/Anime/Index.cshtml
<div class="text-center">
    <h1 class="display-4">Animes</h1>
</div>

<div id="app">
    <div v-if="isAuthorized" class="row">
        <div class="col-md-12">
            <div class="alert alert-info" v-if="feedback">
                {{feedback}}
            </div>
        </div>
        <div class="col-md-12">
            <button class="btn btn-secondary btn-block w-25" v-on:click.prevent="toEditMode(false)">New</button>
        </div>

        <div class="col-md-6">
            <ul class="list-group">
                <li class="list-group-item list-group-item-action" v-for="anime in animes" v-on:click="getAnimeDetails(anime)">
                    <div class="d-flex w-100 justify-content-between">
                        <h5>
                            {{anime.title}}
                            <small>({{anime.releaseYear}})</small>
                        </h5>
                    </div>
                    <p class="mb-1">{{anime.description}})</p>
                </li>
            </ul>
        </div>

        <div class="col-md-6">
            <div v-if="currentAnime">
                <div class="form-group">
                    <label>Title</label>
                    <input class="form-control" v-model="currentAnime.title" v-bind:readonly="isReadOnly" />
                </div>
                <div class="form-group">
                    <label>Release year</label>
                    <input type="number" class="form-control" v-model="currentAnime.releaseYear" v-bind:readonly="isReadOnly" />
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <textarea class="form-control" v-model="currentAnime.description" v-bind:readonly="isReadOnly" rows="3"></textarea>
                </div>
                <div class="form-group">
                    <label>Genre</label>
                    <input class="form-control" v-if="isReadOnly" v-model="currentAnime.genre.name" v-bind:readonly="isReadOnly" />
                    <select v-else class="form-control" v-model="currentAnime.genre" v-bind:readonly="isReadOnly">
                        <option v-for="genre in genres" v-bind:value="genre">{{genre.name}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Language</label>
                    <input class="form-control" v-if="isReadOnly" v-model="currentAnime.language.name" v-bind:readonly="isReadOnly" />
                    <select v-else class="form-control" v-model="currentAnime.language" v-bind:readonly="isReadOnly">
                        <option v-for="language in languages" v-bind:value="language">{{language.name}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Seasons</label>
                    <input type="number" class="form-control" v-model="currentAnime.seasons" v-bind:readonly="isReadOnly" />
                </div>
                <div class="form-group">
                    <label>Total episodes</label>
                    <input type="number" class="form-control" v-model="currentAnime.totalEpisodes" v-bind:readonly="isReadOnly" />
                </div>
                <div class="form-group">
                    <label>Does it have english subtitles?</label>
                    <input type="checkbox" class="form-control" v-model="currentAnime.hasSub" v-bind:disabled="isReadOnly" />
                </div>
                <div class="btn-group">
                    <button class="btn btn-warning" v-if="isReadOnly" v-on:click.prevent="toEditMode(true)">Edit</button>
                    <button class="btn btn-warning" v-if="!isReadOnly" v-on:click.prevent="saveAnime">Save</button>
                    <button class="btn btn-primary" v-if="!isReadOnly" v-on:click.prevent="isReadOnly = true">Cancel</button>
                    <button class="btn btn-danger" v-on:click.prevent="deleteAnime">Delete</button>
                </div>
            </div>
        </div>
    </div>
    <div v-else>
        <div class="col-md-offset-1">
            <div class="alert alert-danger text-xl-center">
                <h4 class="alert-heading">You are not authorized to see this page!</h4>
                <p>Please contact an admin for more info</p>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/lib/vue/vue.js"></script>
    <script src="~/lib/axios/axios.min.js"></script>

    <script>

        const apiURL = apiBase + animeEndpoint;
        var token = sessionStorage.getItem('jwtToken');
        const axiosConfig = { headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" } };

        var app = new Vue({
            el: "#app",
            data: {
                animes: null,
                genres: null,
                languages: null,
                currentAnime: null,
                isReadOnly: true,
                isEditMode: false,
                feedback: '',
                isAuthorized: true
            },
            created:
                function () {
                    var self = this;
                    console.log(apiBase);
                    self.fetchAnimes();
                    self.fetchGenres();
                    self.fetchLanguages();
                },
            methods: {
                fetchAnimes: function () {
                    var self = this;
                    axios
                        .get(apiURL, axiosConfig)
                        .then(function (response) {
                            console.log(token);
                            self.animes = response.data;
                            self.isAuthorized = true;
                        })
                        .catch(function (error) {
                            if (error.response.status === 403 || error.response.status === 401) {
                                self.isAuthorized = false;
                                console.log(error);
                            }
                        });
                },
                fetchGenres: function () {
                    var self = this;
                    axios
                        .get(`${apiBase}${genreEndpoint}`, axiosConfig)
                        .then(function (response) {
                            self.genres = response.data;
                        })
                        .catch(function (error) {
                            console.error(error);
                        });
                },
                fetchLanguages: function () {
                    var self = this;
                    axios
                        .get(`${apiBase}${languageEndpoint}`, axiosConfig)
                        .then(function (response) {
                            self.languages = response.data;
                        })
                        .catch(function (error) {
                            console.error(error);
                        });
                },
                getAnimeDetails: function (anime) {
                    var self = this;
                    self.currentAnime = anime;
                },

                toEditMode: function (isEditMode) {
                    var self = this;
                    self.isReadOnly = false;
                    self.isEditMode = isEditMode;

                    if (!self.isEditMode) {
                        self.currentAnime = {
                            title: "",
                            releaseYear: "",
                            description: "",
                            genre: "",
                            language: "",
                            seasons: "",
                            totalEpisodes: ""
                        }
                    }
                },

                saveAnime: function () {
                    var self = this;

                    console.log(self.currentAnime);
                    let animeToSend = {
                        id: self.currentAnime.id,
                        title: self.currentAnime.title,
                        releaseYear: parseInt(self.currentAnime.releaseYear),
                        description: self.currentAnime.description,
                        image: "no image at the moment",
                        genreId: self.currentAnime.genre.id,
                        languageId: self.currentAnime.language.id,
                        seasons: parseInt(self.currentAnime.seasons),
                        totalEpisodes: parseInt(self.currentAnime.totalEpisodes),
                        hasSub: self.currentAnime.hasSub
                    }

                    if (self.isEditMode) {
                        var url = `${apiURL}`;
                        console.log(animeToSend);
                        axios.put(url, animeToSend, axiosConfig)
                            .then(function (response) {
                                self.feedback = `Anime ${self.currentAnime.title} has been modified`;
                            })
                            .catch(function (error) {
                                if (error.response.status === 403 || error.response.status === 401) {
                                    self.feedback = `You are not authorized to modify an anime`;
                                    console.log(error);
                                }
                            })
                            .then(function () {
                                self.isReadOnly = true;
                                setTimeout(function () { self.feedback = null; }, 3000);
                            });
                    }
                    else {
                        var url = `${apiURL}`;
                        axios.post(url, animeToSend, axiosConfig)
                            .then(function (response) {
                                self.feedback = `Anime ${self.currentAnime.title} has been created`;
                                self.animes.push(self.currentAnime); // update animes
                            })
                            .catch(function (error) {
                                if (error.response.status === 403 || error.response.status === 401) {
                                    self.feedback = `You are not authorized to create an anime`;
                                    console.log(error);
                                }
                            })
                            .then(function () {
                                self.isReadOnly = true;
                                setTimeout(function () { self.feedback = null; }, 3000);
                            });
                    }
                },
                deleteAnime: function () {
                    var self = this;
                    var url = `${apiURL}/${self.currentAnime.id}`;

                    axios.delete(url, axiosConfig)
                        .then(function (response) {
                            self.animes.forEach(function (anime, i) {
                                if (anime.id === self.currentAnime.id) {
                                    self.animes.splice(i, 1); // update animes
                                    self.currentAnime = {
                                        title: "",
                                        releaseYear: "",
                                        description: "",
                                        genre: "",
                                        language: "",
                                        seasons: "",
                                        totalEpisodes: ""
                                    }
                                    self.feedback = `Anime ${self.currentAnime.title} has been deleted`;
                                    setTimeout(function () { self.feedback = null; }, 3000);
                                }
                            })
                        })
                        .catch(function (error) {
                            if (error.response.status === 403 || error.response.status === 401) {
                                self.feedback = `You are not authorized to delete an anime`;
                                console.log(error);
                            }
                            console.error(error);
                        })
                },
            }
        });
    </script>
}

src/Imi.Project.Vue/Views/Director/Index.cshtml
<div class="text-center">
    <h1 class="display-4">Directors</h1>
</div>

<div id="app" >
    <div v-if="isAuthorized" class="row">
        <div class="col-md-12">
            <div class="alert alert-info" v-if="feedback">
                {{feedback}}
            </div>
        </div>
        <div class="col-md-12">
            <button class="btn btn-secondary btn-block w-25" v-on:click.prevent="toEditMode(false)">New</button>
        </div>

        <div class="col-md-6">
            <ul class="list-group">
                <li class="list-group-item list-group-item-action" v-for="director in directors" v-on:click="getDirectorDetails(director)">
                    {{director.name}}
                </li>
            </ul>
        </div>

        <div class="col-md-6">
            <div v-if="currentDirector">
                <div class="form-group">
                    <label>Name</label>
                    <input class="form-control" v-model="currentDirector.name" v-bind:readonly="isReadOnly" />
                </div>
                <div class="btn-group">
                    <button class="btn btn-warning" v-if="isReadOnly" v-on:click.prevent="toEditMode(true)">Edit</button>
                    <button class="btn btn-warning" v-if="!isReadOnly" v-on:click.prevent="saveDirector">Save</button>
                    <button class="btn btn-primary" v-if="!isReadOnly" v-on:click.prevent="isReadOnly = true">Cancel</button>
                    <button class="btn btn-danger" v-on:click.prevent="deleteDirector">Delete</button>
                </div>
            </div>
        </div>
    </div>
    <div v-else>
        <div class="col-md-offset-1">
            <div class="alert alert-danger text-xl-center">
                <h4 class="alert-heading">You are not authorized to see this page!</h4>
                <p>Please contact an admin for more info</p>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/lib/vue/vue.js"></script>
    <script src="~/lib/axios/axios.min.js"></script>

    <script>
        const apiURL = apiBase + directorEndpoint;
        var token = sessionStorage.getItem('jwtToken');
        const axiosConfig = { headers: { Authorization: `Bearer ${token}` } };

        var app = new Vue({
            el: "#app",
            data: {
                directors: null,
                currentDirector: null,
                isReadOnly: true,
                isEditMode: false,
                feedback: '',
                isAuthorized: true
            },
            created:
                function () {
                    var self = this;
                    console.log(apiBase);
                    self.fetchDirectors();
                },
            methods: {
                fetchDirectors: function () {
                    var self = this;
                    axios
                        .get(apiURL, axiosConfig)
                        .then(function (response) {
                            console.log(token);
                            self.directors = response.data;
                            self.isAuthorized = true;
                        })
                        .catch(function (error) {
                            if (error.response.status === 403 || error.response.status === 401) {
                                self.isAuthorized = false;
                                console.log(error);
                            }
                        });
                },
                getDirectorDetails: function (director) {
                    var self = this;
                    self.currentDirector = director;
                },

                toEditMode: function (isEditMode) {
                    var self = this;
                    self.isReadOnly = false;
                    self.isEditMode = isEditMode;

                    if (!self.isEditMode) {
                        self.currentDirector = {
                            name: ""
                        }
                    }
                },

                saveDirector: function () {
                    var self = this;

                    if (self.isEditMode) {

                        var url = `${apiURL}`;
                        axios.put(url, self.currentDirector, axiosConfig)
                            .then(function (response) {
                                self.feedback = `Director ${self.currentDirector.name} has been modified`;
                            })
                            .catch(function (error) {
                                if (error.response.status === 403 || error.response.status === 401) {
                                    self.feedback = `You are not authorized to modify a director`;
                                    console.log(error);
                                }
                            })
                            .then(function () {
                                self.isReadOnly = true;
                                setTimeout(function () { self.feedback = null; }, 3000);
                            });
                    }
                    else {
                        var url = `${apiURL}`;
                        axios.post(url, self.currentDirector, axiosConfig)
                            .then(function (response) {
                                self.currentDirector = response.data;
                                self.feedback = `Director ${self.currentDirector.name} has been created`;
                                self.directors.push(self.currentDirector); // update directors
                            })
                            .catch(function (error) {
                                if (error.response.status === 403 || error.response.status === 401) {
                                    self.feedback = `You are not authorized to create a director`;
                                    console.log(error);
                                }
                                console.error(error);
                            })
                            .then(function () {
                                self.isReadOnly = true;
                                setTimeout(function () { self.feedback = null; }, 3000);
                            });
                    }
                },
                deleteDirector: function () {
                    var self = this;
                    var url = `${apiURL}/${self.currentDirector.id}`;

                    axios.delete(url, axiosConfig)
                        .then(function (response) {
                            self.directors.forEach(function (director, i) {
                                if (director.id === self.currentDirector.id) {
                                    self.directors.splice(i, 1); // update directors
                                    self.currentDirector = {
                                        name: ""
                                    }
                                    self.feedback = `Director ${self.currentDirector.name} has been deleted`;
                                    setTimeout(function () { self.feedback = null; }, 3000);
                                }
                            })
                        })
                        .catch(function (error) {
                            if (error.response.status === 403 || error.response.status === 401) {
                                self.feedback = `You are not authorized to delete a director`;
                                console.log(error);
                            }
                            console.error(error);
                        })
                },
            }
        });
    </script>
}

src/Imi.Project.Vue/Views/Home/Index.cshtml
<div class="text-center">
    <h1 class="display-4">Welcome to MyWatchList</h1>
</div>

<div id="app">
    <div v-if="!isLoggedIn" class="text-center">
        <a class="btn btn-success" href="/User/Login" role="button">Login</a>
        <a class="btn btn-secondary" href="/User/Register" role="button">Register</a>
    </div>
    <div v-else class="text-center">
        <p>You are logged in!</p>
        <a class="btn btn-danger" href="/User/Logout" role="button">Logout</a>
    </div>
</div>

@section scripts{
    <script src="~/lib/vue/vue.js"></script>
    <script src="~/lib/axios/axios.min.js"></script>

    <script>
        var token = sessionStorage.getItem('jwtToken');

        var app = new Vue({
            el: "#app",
            data: {
                isLoggedIn: false
            },
            mounted: function () {
                var self = this;
                console.log(token);
                self.checkIfLoggedIn();
            },
            methods: {
                checkIfLoggedIn: function () {
                    var self = this;
                    self.token = sessionStorage.getItem('jwtToken');
                    if (token == null) {
                        self.isLoggedIn = false;
                    }
                    else {
                        self.isLoggedIn = true;
                    }
                    console.log(self.isLoggedIn);
                }
            }
        });
    </script>
}

src/Imi.Project.Vue/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="~/js/myConstants.js"></script>
    <title>@ViewData["Title"] - Imi.Project.Vue</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Imi.Project.Vue</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Anime" asp-action="Index">Anime</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genre" asp-action="Index">Genre</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Director" asp-action="Index">Director</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TopTenMovies" asp-action="Index">Top 10 movies</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Imi.Project.Vue - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

src/Imi.Project.Vue/Views/TopTenMovies/Index.cshtml
<div class="text-center">
    <h1 class="display-4">Top 10 movies</h1>

</div>

<div id="app" class="row justify-content-center">

    <div v-for="movie in topMovies">
        <div class="card mb-3" style="max-width: 640px;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img v-bind:src='"https://www.themoviedb.org/t/p/w220_and_h330_face" + movie.poster_path' class="card-img" alt="...">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{movie.title}} - {{movie.vote_average}}</h5>
                        <p class="card-text">{{movie.overview}}</p>
                        <p class="card-text"><small class="text-muted">Vote count: {{movie.vote_count}}</small></p>
                    </div>
                </div>

            </div>

        </div>

    </div>
</div>

@section scripts{
    <script src="~/lib/vue/vue.js"></script>
    <script src="~/lib/axios/axios.min.js"></script>

    <script>
        var apiURL = 'https://api.themoviedb.org/3/movie/top_rated?api_key=6ebfdabc3787595e36413cfef5b5ceec&language=en-US&page=1';

        var app = new Vue({
            el: '#app',
            data: {
                movies: null,
                topMovies: null,
                imageUrl: null

            },
            created: function () {
                var self = this;
                self.fetchMovies();
            },
            methods: {
                fetchMovies: function () {
                    var self = this;

                    axios.get(`${apiURL}`)
                        .then(function (response) {
                            self.movies = response.data.results;
                            self.topMovies = self.movies.splice(0, 10);
                        })
                        .catch(function (error) {
                            console.error(error);
                        });
                },
                getImage: function (movie) {
                    let baseUrl = "https://image.tmdb.org/t/p/w600_and_h900_bestv2/";
                    self.imageUrl = `${baseUrl}{movie.poster_path}`;

                    return self.imageUrl;
                }
            }
        });
    </script>
}